#!/usr/bin/env python3
"""42-label-tree.py — apply SELinux labels + ownership/mode to a staging tree.

SELinux: parsed from the partition's *_file_contexts (first-match-wins,
exactly like libselinux at build time). Applied with setfattr -h (links too).
Ownership/mode: from --meta-tsv (path uid gid mode, octal mode), generated by
  43-dump-meta.py from the ORIGINAL image; entries missing from the TSV get
  AOSP fs_config_generator defaults (dirs 0755 root:root, files 0644 root:root,
  symlinks root:root untouched mode).
Transplants: covered automatically — same regexes + defaults apply; add explicit
  overrides to build/transplant-meta-overrides.tsv if a transplant needs them.

Usage: 42-label-tree.py <stage-root> <file-contexts> [--meta-tsv F] [--report OUT]
Writes report: labeled count, defaulted count, unmatched-label count.
"""
import os
import re
import subprocess
import sys


def load_fc(path):
    entries = []
    for line in open(path, encoding="utf-8", errors="replace"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("genfscon"):
            continue
        parts = line.split()
        if len(parts) < 2:
            continue
        regex, ctx = parts[0], parts[-1]
        try:
            entries.append((re.compile(regex), ctx, regex))
        except re.error:
            pass
    return entries


def load_meta(path):
    meta = {}
    if not path:
        return meta
    for line in open(path):
        p = line.rstrip("\n").split("\t")
        if len(p) >= 4:
            try:
                meta[p[0]] = (int(p[1]), int(p[2]), int(p[3], 8))
            except ValueError:
                pass
    return meta


def setxattr(path, name, value, symlink):
    cmd = ["setfattr", "-n", name, "-v", value, path]
    if symlink:
        cmd.insert(1, "-h")
    r = subprocess.run(cmd, capture_output=True)
    return r.returncode == 0


def main(root, fc_path, meta_tsv=None, report=None, prefix="", fallback_fc=None):
    fc = load_fc(fc_path)
    fcb = load_fc(fallback_fc) if fallback_fc else []
    meta = load_meta(meta_tsv)
    n_lab = n_def = n_unmatch = n_own = n_fb = 0
    problems = []
    for dp, dns, fns in os.walk(root, followlinks=False):
        for name in dns + fns:
            full = os.path.join(dp, name)
            rel = "/" + os.path.relpath(full, root)
            devpath = prefix + rel  # absolute on-device path for file_contexts match
            meta_key = rel.lstrip("/")  # path relative to partition root (matches meta TSV)
            is_link = os.path.islink(full)
            is_dir = os.path.isdir(full) and not is_link
            hit = None
            for rx, ctx, _src in fc:
                if rx.match(devpath):
                    hit = ctx
                    break
            if hit is None:
                for rx, ctx, _src in fcb:
                    if rx.match(devpath):
                        hit = ctx
                        n_fb += 1
                        break
            if hit:
                if setxattr(full, "security.selinux", hit, is_link):
                    n_lab += 1
                else:
                    problems.append(f"XATTR-FAIL {devpath}")
            else:
                n_unmatch += 1
                problems.append(f"NO-LABEL {devpath}")
            if meta_key in meta:
                uid, gid, mode = meta[meta_key]
                try:
                    if not is_link:
                        os.chown(full, uid, gid, follow_symlinks=False)
                        os.chmod(full, mode, follow_symlinks=False)
                    else:
                        os.chown(full, uid, gid, follow_symlinks=False)
                    n_own += 1
                except PermissionError:
                    problems.append(f"CHOWN-FAIL (need root?) {devpath}")
            else:
                n_def += 1
                try:
                    if not is_link:
                        if is_dir:
                            os.chmod(full, 0o755, follow_symlinks=False)
                        else:
                            os.chmod(full, 0o644, follow_symlinks=False)
                except OSError as e:
                    problems.append(f"CHMOD-FAIL {devpath}: {e}")
    rep = [f"labeled={n_lab} fallback={n_fb} default-mode={n_def} no-label-match={n_unmatch} meta-owned={n_own}",
           f"problems={len(problems)}"] + problems[:50]
    if report:
        open(report, "w").write("\n".join(rep) + "\n")
    print("\n".join(rep[:8]))


if __name__ == "__main__":
    a = sys.argv[1:]
    if len(a) < 2:
        sys.exit("usage: 42-label-tree.py <stage-root> <file-contexts> [--meta-tsv F] [--report OUT] [--prefix /system_ext]")
    mt = a[a.index("--meta-tsv") + 1] if "--meta-tsv" in a else None
    rp = a[a.index("--report") + 1] if "--report" in a else None
    px = a[a.index("--prefix") + 1] if "--prefix" in a else ""
    fb = a[a.index("--fallback-fc") + 1] if "--fallback-fc" in a else None
    main(a[0], a[1], mt, rp, px, fb)
